### ISSUE TITLE
Sửa lại Menu liên quan đến Knowlegde trên AdminDashboard

### ISSUE THREAD

**Issue by denny1507** [nhanleelab/ga-mcovid#2]
Nội dung sửa đổi như sau:
- Bỏ menu level 2 "Category"
- Sửa All Module -> All Categories
- Sửa New Knowlegde -> New Category

Trong màn hình New Category (là màn hình New Knowlegde hiện tại):
Ở group "Categories & Tags":  bỏ phần Categories và giữ lại phần Tag

**Comment by stevenlee2806** [comment]
@finn1310 em fix theo comment của a Huynh nhé

**Comment by itsminh99** [comment]
Đã sửa.
