### ISSUE TITLE
[CA]- Không hiển thị đủ các Learning khi tạo Capsule

### ISSUE THREAD

**Issue by DuongThiHuongSen** [nhanleelab/ga-mcovid#30]
**Bug ID**: CR-CA-002
**Date**: 18/09/2020
**Status**: New
**Summary:** Lỗi hiển thị các bản ghi khi nhấn Choose Learning
**Description**: Khi người dùng chọn choose Learning, không show hết các learning hiện có.
**Step to reproduce**:
  1. Đăng nhập thành công vào giao diện trang Addmin.
  2. Hover trên **LEARNING**.
  3. Chọn **NEW CAPSULE**.
  4. Chọn **Choose Learning**.
  5. Kiểm tra kết quả 

**Expected results**: Hiển thị đúng mô tả số lượng bản Learning đang có.

**Comment by itsminh99** [comment]
Số lượng data có thể rất lớn. Không cho phép hiện tất cả.
