### ISSUE TITLE
[MB_CS] Lỗi không hiển thị được Capsules

### ISSUE THREAD

**Issue by thuongdt** [nhanleelab/ga-mcovid#44]
Bug ID: MB_CS_012
Date: 08/10/2020
Assigned to: Thắng
Status: New
Summary:  Lỗi không hiển thị được Capsules
Description: Click vào Learning -> Chọn Capsule 
Environments(OS/Browser): Mobile
Step to reproduce:

1. Đăng nhập vào app mobile
2. Chọn Learning
3. Chọn Capsule
4. Thông tin Capsule không hiển thị
Expected results:  Hiển thị đầy đủ nội dung của Capsule đó

![BugCapsule](https://user-images.githubusercontent.com/50014716/95477712-d4907e00-09b2-11eb-9d85-0a7660bebaa9.png)

**Comment by haithanvan** [comment]
không thấy còn bị lỗi nữa
